### ISSUE TITLE
Multilingual navigation links issue

### ISSUE THREAD

**Issue by key-notes** [getgrav/grav-premium-issues#111]
I'm not sure if this is an issue with the Typhoon theme or with Grav in general, but I'll try posting it here. A very useful feature of Typhoon (or Grav in general?) is the ability to create empty parent pages specifically for use as menu items.

For example, the link "About" might itself be blank, while still containing submenu items such as "History," "Team," "Press," etc. The page titled "About" contains no default.md page, so Grav ignores it but uses it only for the dropdown menu. "About" is not clickable but its sub-pages are.

This appears to work only if the site is in one language. For multilingual sites, the default language is always shown for these empty dropdown links.

The only workaround I can see so far would be to make these "real" pages, but that requires extra complexity.

Is there a better solution? Is this a bug or an oversight?

**Comment by w00fz** [comment]
This is a fairly common scenario and all you have to do is to set your Parent page (the one you don't want anyone to access to / click on) and set it to non-routable. 

In admin you would find this option under `Advanced -> Overrides -> Routable` (set it to Disabled). 
In the frontmatter this translates to `routable: false`.

You will also want to make sure the Children that you want to appear in a submenu are set as visible.

This in turns will create a Parent menu item that cannot be reached directly since it's non routable, and Children that can be clicked on and can be reached at as regular pages.

Note also that non routable pages are still pages, so in the future if you will ever decide that you do want said page to turn into a landing page of sort, all you need to do is to add some content and make it routable again.


I hope this answers your question!

**Comment by key-notes** [comment]
@w00fz: Oh, that's really easy—thanks so much!

For anyone finding this later who might have the same question, all we need to do for the non-primary languages then is to add `title: Foreign Language Title` and `routable: false` to the frontmatter (replacing "Foreign Language Title" with the actual title).

**Comment by w00fz** [comment]
No problem and thanks for the additional information!
