### ISSUE TITLE
[typhoon] How to add custom heading font?

### ISSUE THREAD

**Issue by key-notes** [getgrav/grav-premium-issues#114]
How can we add a custom heading font to the Typhoon theme? In principle it should be a cinch, though it seems I haven't quite grasped how Grav parses all its files.

I created a full copy of Typhoon (according to the instructions, _not_ using 'inheritance') and added the following to `/css/custom`:

`@font-face {`
    `font-family: 'Pinyon Script', cursive;`
    `font-weight: 400;`
    `font-display: swap;`
    `font-style: normal;`
    `font-named-instance: 'Regular';`
    `src: url("../../fonts/PinyonScript.woff2") format("woff2");`
`}`

`h1 {`
    `font-family: 'Pinyon Script' !important;`
`}`

I also uploaded PinyonScript.woff2 to `/fonts`, but the font doesn't seem to get loaded. The command `npm run watch` is currently running and outputs in part `> postcss css/site.css -o build/css/site.css --watch`.

Is there an "official" way to add a custom font only to header tags using this theme? Many thanks in advance for any help.

**Comment by rhukster** [comment]
This is probably a good one to document, so I've noted it here, but the recommended approach is:


1. Enable the **watch** command: `npm run watch`
2. Add your font to the `fonts/` folder. These days you only need `.woff2` version and you are good for all modern browsers. e.g. `Sora-VariableFont_wght.ttf`
3. Add the `@font-face` definition in the `css/custom/fonts.css` file. Make sure the filename exactly matches the filename of the font file you added. e.g.
  ```css
  @font-face {
    font-family: 'Sora var';
    src: url("../../fonts/Sora-VariableFont_wght.ttf?v=3.12") format("truetype");
    font-weight: 100 900;
    font-display: swap;
    font-style: normal;
  }
  ```
4.  In your `tailwind.config.js` file, look fo the `fontFamily: { ... }` block where there's an existing `sans` definition.  Simply add another entry below this can call it anything, for this example we'll use `title:`:
  ```js
  fontFamily: {
    sans: [
      ...
    ],
    title: [
      'Sora Var', 
      'sans-serif',
    ],
  },
  ```
  This creates a new `font-family` definition inside Tailwind.  
5. Now edit your `css/custom/typography.css` file and add a definition to assign all headers this new font style. e.g.:
  ```css
  h1, h2, h3, h4, h5, h6 {
    @apply font-title;
  }
  ```
6. Rebuild if you have not already had a watch started.  `npm run build`
7. You might find your font is not displaying due to browser cache,  Hold `SHIFT` and and click **Reload** icon.
