### ISSUE TITLE
[seo-magic] Meta Description auto generation not working for modules

### ISSUE THREAD

**Issue by drscream** [getgrav/grav-premium-issues#117]
If I use pages which contains modules for text the auto generated meta description (and keywords) does not use content from these modules. At the end the auto generated meta description only contains information from the menu and some headers which are described in this page.

### Reproduce

1. Create one page with page template "modular"
2. Add "module" for this generated page with template "text"
3. Add some text to the new module
4. Automatically generate the SEO description and keywords

**Comment by rhukster** [comment]
because modular sub-pages only contribute to creating a single modular, the metadata needs to be set on the parent 'modular' page, not the modular sub-pages.

**Comment by drscream** [comment]
But shouldn't be the page meta description contains the text from the modules in this page?

**Comment by rhukster** [comment]
Short answer is no, but that's only because we decided it made more sense to keep the 'page meta description' at the page level.  It would be hard to manage if you had a variety of meta descriptions in sub-modular pages and they were being combined into one big description.  You wouldn't know where they came from without having to hunt through each sub-modular page.
