### ISSUE TITLE
[typhoon] Pagination back and forward buttons are outside the viewport on mobile

### ISSUE THREAD

**Issue by GilbN** [getgrav/grav-premium-issues#120]
When the page count is above a certain amount the next and back buttons are outside the viewport.
![](https://selfhosted.app/f3c10/WUWiFoxU20.png/raw)
Example: https://grav.spad.uk/blog/

grav: version: 1.7.9
typhoon v2.0.1

**Comment by rhukster** [comment]
While this could be fixed in the theme by forcing the pagination numbers to wrap on smaller displays, the better option would be to use the `delta` option in the **pagination** plugin.

Per the `README.md` of pagination:

```
enabled: true
built_in_css: true
delta: 0
```

The 'delta' value controls how many pages left and right of the current page are visible. If set to 0 all pages will be shown.

**Comment by GilbN** [comment]
Thanks! Yeah that works great. 👍
