### ISSUE TITLE
[nextgen-editor] Touches height/weight in html blocks

### ISSUE THREAD

**Issue by xf-** [getgrav/grav-premium-issues#125]
This is a different behavior than original editor and causes problems.

## BBefore saving
```html
<img alt="yes" class="some-classes" src="foobar.jpg" width="350" height="350">
```

## After saving with editor
```html
<img alt="yes" class="some-classes" src="foobar.jpg">
```

Maybe with also having the other issue with twig → stop touching some stuff inside HTML block.

**Comment by w00fz** [comment]
This is caused by our `action:convertUrls` who returns the string with the stripped width/html.

**Comment by w00fz** [comment]
After digging into this more, I can see this is an expected behavior. When saving, the whole content gets markdown processed and although HTML is allowed, URL for links and images are still going to be processed to allow to use our advanced Media library. When this happens via the `parsedown` library, those attributes get removed because in Markdown you cant have width/height for an image and there's nothing we can do about it.

That said there are two ways you can work around this:

1. If you are looking to just ensure your image renders with a certain width/height, you can use the Grav Media API to do so. This will created a resized, cached version of your original image to that exact size, in your case this would be:

    ```html 
    <img alt="yes" class="some-classes" src="image.webp?cropResize=350,350">
    ```
    Note that this still won't add width/height attributes. 
    
    More info: https://learn.getgrav.org/17/content/media
2. If you are looking to have width/height attributes for all of your images on your site, for better scores, etc, then you should look into the `auto_sizes` option that comes with Grav. Once enabled it will take care of it automatically for all images.

    More info: https://learn.getgrav.org/17/basics/grav-configuration#images

**Comment by xf-** [comment]
@w00fz this was mainly an issue in HTML blocks. No height/weight attribute result in necessary movement of content while loading. This is not a good solution. Especially with any lazy attribute or intersection observer. You want to reserve the space/area for that image and use some class with responsive behavior for the image. I would be fine if grav adds the sizes to all images, so the ratio is set.

e.g. Lighthouse in chrome or web.dev (Google)
https://learn.getgrav.org/17/content/media

**Comment by w00fz** [comment]
This is why I was suggesting enabling `auto_sizes`, that's exactly to prevent content reflow and will not penalize your score. If that's the reason you should go with option 2 rather than manually specifying sizes to each image in your content.

**Comment by xf-** [comment]
I will test it later.
- What will happen with image on another server CDN?
- What will happen wiht SVGs?

**Comment by w00fz** [comment]
SVG are not a problem, the width/height is already defined within. Regarding CDN you might have to try but that should work too.
