### ISSUE TITLE
[instagram-feed] what filters are available for feeds?

### ISSUE THREAD

**Issue by hughbris** [getgrav/grav-premium-issues#126]
I don't own this plugin yet or know if this is the preferred way to find information about the plugin's functionality.

Specifically wondering if I will be able to only pull feed items based on hashtags. Doesn't look like the library you use supports it, worth checking though. There might be a kludge.

More generally, should I make feature requests and raise questions like this about premium plugins on the issue tracker here? Is there a way to submit PRs if I was to improve something?

**Comment by hughbris** [comment]
As luck would have it, I've since come across better information after submitting this not long ago.

> "If you are building an app that will allow Instagram Businesses or Creators to publish media, moderate comments, identify @mentioned and hashtagged media, or get data about other Instagram users, use the Instagram Graph API instead."
https://developers.facebook.com/docs/instagram-basic-display-api/

Seems like it's the Basic API that doesn't support hashtag filtering, _\*groan\*_.

The [InstagramBasicDisplayApi library](https://github.com/nbcommunication/InstagramBasicDisplayApi#getrecentmediabytagstring-tag-string-username) does provide such a method by kludge but does not recommend it.

I'm still interested in my more general questions though, so please address them before closing this. Cheers.

**Comment by rhukster** [comment]
This is something that I would need to research in more detail.  I don’t have a food answer for you at the mo.

**Comment by w00fz** [comment]
### Hashtag Filtering
The Graph API is actually aimed to a more professional/business like and creators audience. The API allows for full control over the account, including publishing/un-publishing entries, search, filter and so on. I think the process of approval is also slightly more involved.

It is a bit out of the scope of what Instagram Feed is supposed to be which is a way to display an Instagram list of media in view-only mode from your account.

That method you found for the library used is definitely something we could provide with the plugin but I can totally see why it is not recommended, it's kinda brute-forcing its way into collecting the tagged insta posts in a non efficient way. Most likely this will turn into the API reaching the rate limit and whatnot. However we do cache all the results and it might work as a solution for specific scenarios and probably where there aren't a huge amount of posts to go through. I will take a look at making this method available via twig at least.

I share with you the frustration, it is extremely limited in what it can do and being able to filter by hashtag would be very useful but like you found out already, this is not possible as the fields available are incredibly limited: https://developers.facebook.com/docs/instagram-basic-display-api/reference/media#fields

Maybe this is something we will revamp in the future where we expand to a wider audience and go through the Graph API instead of Basic API, I do not think this is something we are going to change anytime soon though. The Basic API is also quite young so I wouldn't surprised if they add more filtering functionalities soon. We would definitely jump on that if it becomes an option.

### General questions
It is fine for you to open this kind of questions in this issue tracker, it is meant exactly for that: questions, suggestions, bug reports.
Regarding the PRs, that is a bit more complicated. Since all the source code for the Premium products resides on private repositories, you can't really access them and contribute the way you can with Grav. More to the point we also wouldn't want you to share any code publicly.
If you have any contribution you'd like to provide to a product, just ping Andy or myself via email or discord and we would be more than happy to evaluate it and implement it!

Hope this answers all the questions :)

**Comment by hughbris** [comment]
Thanks, great answers!

I'm just bummed that the Basic API doesn't include these filters. I can't help but be cynical that it's by limited by design to push us to use the Graph API. Pretty sure FB have the resources available to add this if they want :[
