### ISSUE TITLE
[seo-magic] Generate SEO data in admin panel times out

### ISSUE THREAD

**Issue by kees-closed** [getgrav/grav-premium-issues#157]
Since the 3.0 release, the seo-magic plugin times out with the following error in the Chrome console `Failed to load resource: the server responded with a status of 504 () -  at 504 Gateway Time-out` after 2-3 minutes.

However, it does work fine from the CLI. I don't know how to provide much more info, since there is no logging done(?)

Using seo-plugin v3.0.2, Grav v1.7.22,  Admin v1.10.22

**Comment by w00fz** [comment]
@kees-closed The timeout might be caused by the new Link Checker feature and if you have many links and pages on your site, this might take some time. You have to ways to fix this:

1. If you are not interested in the Link Checker you can disable it from the settings. Plugins -> Seo Magic -> Link Checker ->  Disable
2. If you want the feature, try bumping the client timeout (Plugins -> Seo Magic -> Client Timeout). NOTE: this is not to be confused with the Link Check Timeout, which is different.

For a customer with many pages and a lot of external links, all while behind Cloudflare, I found a sweet spot by setting Client Timeout to **30s**.

Let us know if this helps!

**Comment by kees-closed** [comment]
Disabling the link checker indeed restored the usual performance. But even setting the client timeout to 600 seconds (10 minutes) doesn't seem to matter. It times out within 1-3 minutes anyway. I may have a special use case though, [this page](https://www.zeitgeistbeweging.nl/tzm/over-tzm) on my Grav instance has a lot of links. That might trigger something unusual perhaps?

Just to test all angles, I bumped the link check timeout to 100 seconds as well. Timeout still happens within 1-3 minutes. For now I'll disable the link checker.

**Comment by rhukster** [comment]
It really comes down to your content.  As the name implies, the link checker checks all the links on the page.  If you have lots of links, or lots of pages, or lots of pages with lots of links, it's going to take the link-checker some time to process.  If it works fine in the CLI, then it might be something related to timeouts on your webserver.  SEO-Magic has options to control how long the HTTP client will wait for link-checking requests to return, but has not control over how long the webserver will wait before the Ajax request to kick of the process times out.
