### ISSUE TITLE
[typhoon] Custom menu

### ISSUE THREAD

**Issue by PepaR** [getgrav/grav-premium-issues#190]
I need use one-page for home and blog for notes in one web. Is it some simple way how replace top menu to custom items, for example: Home | Blog | Custom page | External link, please?

I tried steps in Typhoon Documentation (Programatic Menu Items), so eror occured.

**Comment by rhukster** [comment]
Because Typhoon's menu system is quite powerful and supports many options, the best apporach is to use the Programatic menu solution.

Assuming you have copied Typhoon using devtools, i'm going to assume your theme is called `mytheme`.  So simply open up the `user/themes/mytheme/mytheme.php` file, and add this code at line 79 (right after the `$menu = $event['menu'];` code:

```php
        // Dummy Blog Menu
        $link = new SiteMenuItem();
        $link->text = 'Blog';
        $link->href = Utils::url('/blog');
        $link->id = \Grav\Common\Inflector::hyphenize($link->text);
        $menu->{$link->id} = $link->toArray();
```

The only essential parts are the `text` and the `href`, the `id` in this case is being automatically set based on the `$link->text`.  It can be anything as long as it is unique compared to the other items at the same level.

There are other options you can set like `icon`, `target` etc.  Just look at the examples further down in that `onSiteThemeMenu()` method.

**Comment by PepaR** [comment]
[Thanks a lot. It's working. 

Last questions
1. If I use this code for one-page web, menu item is pernamently underlined and not working as other links in menu for One-Page web (underline when i hoover by mouse)
2. How is possible control color of text this menu item, please? Added item of custom menu has different color then othe item of One-Page.
![Grav_Typhoon_Custom menu](https://user-images.githubusercontent.com/25554468/148677149-0732a214-9a5b-424f-baaf-45d8cee96ca6.png)

**Comment by rhukster** [comment]
You have two options:

In your code disable `active_support`:

```php
// Dummy Blog Menu
$link = new SiteMenuItem();
$link->text = 'Blog';
$link->href = Utils::url('/blog');
$link->active_support = false;
$link->id = \Grav\Common\Inflector::hyphenize($link->text);
$menu->{$link->id} = $link->toArray();
```

or set the `rawroute` properly:

```php
// Dummy Blog Menu
$link = new SiteMenuItem();
$link->text = 'Blog';
$link->href = Utils::url('/blog');
$link->rawroute = Utils::url('/blog');
$link->id = \Grav\Common\Inflector::hyphenize($link->text);
$menu->{$link->id} = $link->toArray();
```

**Comment by PepaR** [comment]
Thanks @rhukster it's working. So unfortunately, if I use it and redirect to the blog, the menu item is duplicated (there is a default and custom link to the blog).

**Comment by PepaR** [comment]
Thanks @rhukster it's working. So unfortunatelly, if I use it and redirect to blog, menu item is duplicated (there is default and custom link to blog).
