### ISSUE TITLE
[typhoon] Change font

### ISSUE THREAD

**Issue by PepaR** [getgrav/grav-premium-issues#191]
Changing font have no affect to webpage. I use steps in Typhoon Documentation and attqch edited files. May you help me please?
[user.zip](https://github.com/getgrav/grav-premium-issues/files/7799858/user.zip)

**Comment by rhukster** [comment]
Your font didn't work for me.  I downloaded it myself from Google, and used that, then it worked fine.  Remember, you need to be running `npm run watch` during this so that it can rebuild the compiled CSS.

<img width="598" alt="CleanShot 2022-01-03 at 13 57 22@2x" src="https://user-images.githubusercontent.com/1084697/147979562-05e61913-ca5e-4a36-8203-611787a7bc9c.png">

Also note that Montserrat is not a **Variable** font, you will need to have a separate `.woff2` file for each font weight you plan on using.

https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face/font-weight

[montserrat-v18-latin-regular.woff2.zip](https://github.com/getgrav/grav-premium-issues/files/7803982/montserrat-v18-latin-regular.woff2.zip)
.

**Comment by PepaR** [comment]
Thaks a lot.
