### ISSUE TITLE
Error with php-zip

### ISSUE THREAD

**Issue by jimbojoho** [getgrav/grav-premium-issues#211]
Recently purchased the Typhoon Theme and plan to use the skeleton provided for download on github. Whilst following the instructions on the github page for installation, I ran into a problem trying to install the ‘license manager’ and ‘admin’ plugins which both show up with the following error message:

`[ERROR] php-zip extension needs to be enabled! `

Can't find an answer in the Grav forums or anywhere else, and with my limited knowledge I'm assuming it's a problem with my macos version (Big Sur). When I get the version number of PHP within terminal it tells me it will soon be unsupported.

Many thanks for your help.

**Comment by rhukster** [comment]
basically your webserver's php does not have php-zip extension with is required for Grav to be able to open zip files.  The built-in version of PHP with macOS is pretty limited, which is why I recommend using the homebrew version which includes all the standard things you need, plus allows you to easily add more.  I have an extensive writeup on this:   

https://getgrav.org/blog/macos-monterey-apache-multiple-php-versions

**Comment by rhukster** [comment]
at a bare minimum you can:

1. install homebrew - https://brew.sh/
2. install php via homebrew - `brew install php`
3. use grav's built in webserver to run grav: `cd /your/grav/install` then `bin/grav server`

**Comment by jimbojoho** [comment]
Thank you so much! Will try the homebrew route for sure. 

Thanks again, much appreciated.
