### ISSUE TITLE
[nextgen-editor] Setting color:white makes child divs unreadable

### ISSUE THREAD

**Issue by angusmcb** [getgrav/grav-premium-issues#215]
Setting 'color' css property of a div to white makes all future text in child divs unreadable, including the heading information.

I think this is best explained with an image:

![Screenshot 2022-02-18 at 11-40-21 Market Based Programming for WASH ( en running-programmes market-based-programming ) Oxfa](https://user-images.githubusercontent.com/58976795/154667317-23852b38-997d-4de3-a93a-33b1c4b787d3.png)

**Comment by w00fz** [comment]
Unfortunately this is not something that I can fix. The CSS gets inherently applied because of its cascading nature. You have a DIV within a DIV and if you parent DIV has text white, anything within it will have text white.

I would strongly suggest you try and use classes instead of hardcoding inline styling. Inline styling is never a good idea, and makes for maintainability a nightmare.
