### ISSUE TITLE
[typhoon] Suggestion: Have menu colors defined in only one place

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#222]
It feels like menu colour adjustments could be easier to track down. The navigation menu colours are spread in couple places:

- There are colours defined in /css/custom/navigation.css (.has-submenu:hover)
- There are colours defined in /templates/blocks/base.html.twig
- There are colours defined in /templates/partials/navigation.html.twig

In that case, css classes would have been easier for customization, and to have one point of reference for the colours; like in navigation.css. You change it there and it is good everywhere in the code.

Kind regards. :-)

**Comment by rhukster** [comment]
There's no real practical way to have all of these in one place.  I think for the most part the dropdown menus should be handled independently as those are complicated and need to be done in CSS (as they already are).  The current Typhoon has sensible defaults for light/dark mode which is basically just a monochrome solution that should work for pretty much any color combos.  If you do need to change the dropdown styling, doing so directly in the CSS makes sense.

The header bar and top-level menu items are a different story, those should be controlled primarily via configuration (for primary colors) and Twig for the complexity of handling all the various configuration options.

There are many scenarios to handle such as: 
* light/dark theme mode
* light/dark/auto header text
* light/dark/auto/custom/transparent header backgrounds
* static/fixed header options that change color based on fixed or scrolling.

As part of the `2.3.0` release of Typhoon and it's support of Fixed headers, i've moved all the color configuration into the top of the `partials/header.html.twig` file instead of being spread out over the header file and also `partials/navigation.html.twig`.  Now it's much easier to understand what's going on and where to change the colors as needed. It's still a bit complicated for the average user, but you can at least make sense of it if you read it carefully:

`partials/header.html.twig`:
```twig
{# Default color values #}
{% set text_class = 'text-gray-800 dark:text-gray-300' %}
{% set menu_class = 'text-gray-700 dark:text-gray-400' %}
{% set active_class = 'text-gray-900 dark:text-white' %}
{% set text_scrolled = text_class %}
{% set hover_class = 'hover:text-primary dark:hover:text-primary' %}

{# Handle "auto text color" as best we can#}
{% if header_text == 'auto' %}
  {% if header_background in  ['dark', 'transparent', 'custom']  %}
    {% set header_text = 'light' %}
  {% elseif header_background == 'light' %}
    {% set header_text = 'dark' %}
  {% endif %}
{% endif %}

{# Set header text colors based on options#}
{% switch header_text %}
  {% case 'dark' %}
    {% set header_text_class = 'text-gray-700' %}
    {% set active_class = 'text-gray-900' %}
  {% case 'light' %}
    {% set header_text_class = 'text-gray-200' %}
    {% set active_class = 'text-white' %}
  {% default %}
    {% set header_text_class = text_class %}
{% endswitch %}

{# set background colors based on option and override as needed#}
{% switch header_background %}
  {% case 'custom' %}
    {% set header_style = 'background: ' ~ header_custom_style ~ ';' %}
    {% set text_scrolled = header_text_class %}
  {% case 'dark' %}
    {% set header_bg_class = 'bg-black/50' %}
    {% set header_bg_scrolled = 'bg-gray-800' %}
    {% set text_scrolled = 'text-gray-200' %}
  {% case 'light' %}
    {% set header_bg_class = 'bg-white/50' %}
    {% set header_bg_scrolled = 'bg-white' %}
    {% set text_scrolled = 'text-gray-800' %}
  {% case 'transparent' %}
    {% set header_bg_class = '' %}
    {% set header_bg_scrolled = 'bg-white dark:bg-gray-800' %}
    {% set active_class = 'text-white' %}
  {% default %} {# auto #}
    {% set header_bg_class = 'bg-white dark:bg-gray-800' %}
    {% set header_bg_scrolled = header_bg_class %}
    {% set active_class = 'text-black dark:text-white' %}
{% endswitch %}
...
```

**Comment by aleclerc7** [comment]
Yes, this is a nice code refactoring and will be easier to customize the colours of the menu.
Thank you for the explanations too.
Best regards.
