### ISSUE TITLE
[seo-magic] Link check deactivated, yet done, and using the devel server address

### ISSUE THREAD

**Issue by aleclerc7** [getgrav/grav-premium-issues#258]
Hello,

In SEO Magic I deactivated the link check, but it still does it.

Also, I saw that all link being checked are still pointing to my devel server instead of the production server.

To update my website I did:
- Install the plugin on my devel server.
- Made my changes.
- Copied the /user folder to the production server.

I was not able to find a setting where the production server would still be used for URL check. Off course, they all fail, and after a moment I get a:

![image](https://user-images.githubusercontent.com/66482588/159606326-984c901c-66c4-4cb2-b16f-dcd259a3bf59.png)

This does so for every local link (grav link): **Idle timeout reached for "https://DEVEL-SERVER-NAME/about/contact".**

Thank you for your help and kind regards.

**Comment by rhukster** [comment]
I think this issue is related to your multi-domain setup specifically.  When the link checker is disabled, it doesn't run. I have tested this today actually, and it works fine.  So this issue is not an seo-magic issue but more likely something related to how you have things setup.

My guess is your multi-domain configurations are not getting picked up period. Admin is not really multi-domain compatible. It really isn't smart enough to know your low-level configuration.  I would check your environement configurations as it's probably saving in a place you are not expecting.  Also check the the debugbar/clockwork debugger and inspect your configuration.  I think you'll find the link checker is still active.

**Comment by aleclerc7** [comment]
Hello,

The configuration is very well set and there is no issue there. This morning, the settings are properly taken into account and SEO Magic is not checking page links anymore.

But the 503 error is still there. When clicking on refreshing SEO Data, the task is never completed. The HTTP 503 error is always displayed after a certain time (maybe a minute or so?).

When I look at Tools -> Log, and Tools -> Report, I see that SEO Magic is **parsing only 6 pages** (in the about section), and that is it. The report contains data on only 5 pages.

I also see in the LOG that it is looping on some pages, for whatever reason.
```
March 23rd at 7:22am | NOTICE | SEOMagic: processed https://domain.tld/a-propos-de/contact/thankyou (200)
March 23rd at 7:22am | NOTICE | SEOMagic: processed https://domain.tld/a-propos-de/contact (200)
March 23rd at 7:22am | NOTICE | SEOMagic: processed https://domain.tld/a-propos-de/liste-de-diffusion (200)
March 23rd at 7:21am | NOTICE | SEOMagic: processed https://domain.tld/a-propos-de (200)
March 23rd at 7:21am | NOTICE | SEOMagic: processed https://domain.tld/a-propos-de/liste-de-diffusion (200)
March 23rd at 7:21am | NOTICE | SEOMagic: processed https://domain.tld/a-propos-de (200)
```

This log is complete. It hangs there with the 503 error. It takes about a minute.

Kind regards.
