### ISSUE TITLE
[Typhoon 1.0.6] Configuration -> Primary Header Levels 

### ISSUE THREAD

**Issue by kiranetph** [getgrav/grav-premium-issues#26]
Level 0 should disable the menu display in the header bar. 
Right now, there is no difference between Value "0" and "1"

**Comment by rhukster** [comment]
I’ll take a look tomorrow.

**Comment by kiranetph** [comment]
Maybe you can consider to increase the range to 8 or 10. 
If someone does not like a side navigation to appear he can just choose the highest value. 5 might be a little low. 
Actually, we have a case on a kiosk navigation where we reach level 5 through a touch screen button navigation.

**Comment by rhukster** [comment]
Regarding levels, 5 is already approaching the limit of what's considered acceptable web UX.  Lots of articles on this, but this is the first one that came up in Google (https://www.uxbooth.com/articles/the-rules-for-modern-navigation/).

Aside from usability, there's the issue of how will it render.  more than 3 levels in a dropdown usually leads to confusion where users very easily 'slip off' the menu mid-navigation, or, the menu itself renders off the page because the primary menu item is too far to the right requiring complex js to switch the direction of the dropdown.  More than another 3 levels is also hard to render in a sidebar because indentation on successive levels means there's less room for text.  I'm afraid that If I up these values too much, people will use them, and then complain that they look bad or are hard to manage :) I'm hesitant to force a sidebar if greater than 3 top levels because I don't want to impose things on users, but it could easily be 

It's a tricky situation to find the balance.  Damned if you do, damned if you don't comes to mind :)

**Comment by kiranetph** [comment]
I agree with the usability in a dropdown navigation.
I just came around the issue of the forced sidebar navigation when playing around with Typhoon for a kiosk project, which uses touch screen buttons and breadcrumbs as main navigation. 

![navigation0](https://user-images.githubusercontent.com/15226809/105889775-837fc500-6049-11eb-9315-e8cb86333324.png)

We have an edge case here, but due to the fact that we can easily modify the limits of the range it does not create a problem. I was just thinking of a way to integrate a solution into the basic functionality. 

For the main issue ( 0/1 level), I still believe that level 0 should disable the navigation display in the header.

**Comment by rhukster** [comment]
I agree, 0 should disable the top 'main' nav and put everything in the side nav.  I will look into that one.

**Comment by rhukster** [comment]
Currently the horizontal-nav works in unision with the side-nav to provide a "split menu" system.  By that I mean that children of the horizontal nav can be shown in the sidebar, but it's not a full menu, it's only a part of it, and it only displays when that menu item is 'active'.

I looked into supporting this approach with no-parent menu items, but it really made the side navigation a mess.  What I came up with was to add a new option to simply set the primary menu to display in the sidebar rather than the horizontal position. This produces the 100% sidebar nav that a 0-primary_levels would, but it's much simpler and cleaner.

This has been added in Typhoon 1.0.8.

**Comment by kiranetph** [comment]
> I agree, 0 should disable the top 'main' nav and put everything in the side nav. I will look into that one.

I just checked the V1.0.8
Value 0 and Value 1 still provide the same result. 
I still believe that a value 0 should disable the menu navigation. Regardless of header or sidebar.
The help tooltip says "The number of level in the primary menu". 
Maybe you can rethink the approach for the next update. To disable the menu completely at value 0 would be the correct behavior, at least in my opinion, and gives the user the disable option as well without introducing another parameter for it.

**Comment by rhukster** [comment]
This is where i disagree with you.  As I struggled to explain in the previous reply, the previous configuration options were to control the "split menu" and how many levels showed in the primary menu as dropdowns (horizontal mode) and when to show levels in the sidebar.  These two parts worked together.  

When there is 0 levels for the primary menu, it never loops over the primary menu, and therefore never even looks for any split menu items.  That is why it's limited to at least have 1 primary menu.  Rather than go down this rabbit whole of changing all that functionality, I feel it makes more sense simply to have a configuration option that says to put the primary menu in the sidebar rather than the horizontal bar, if that is the behavior you want.  It was way less code to do this, and didn't impact the current behavior in any way.

You just need to change your interpretation of what primary menu is and secondary menu.  When you use the primary menu in the header (default), you can split the menu as before.  If you want no horizontal menu, but the full primary menu in the sidebar, then just change the setting for primary menu to sidebar.  

This I think will make sense to most users.

**Comment by kiranetph** [comment]
Thank you for your time to explain. 
Sometimes it is also good to disagree.. ;-)

One possible application of ours just does not require any "traditional" menu, so I was hoping to achieve this behavior without modifying the base template, but since we can freely modify the template to whatever we need, it is not really a big concern. 
Thanks again for the good support.
