### ISSUE TITLE
[seo-magic] SEO Magic tab is not  cascading into Module/text

### ISSUE THREAD

**Issue by ChunkyChats** [getgrav/grav-premium-issues#279]
HI, I'm very new to Grav and SEO Magic. I'm not particularly savvy to the nuances of CSS either, so sorry. The way our template is set up is that we have a cascading menu. the SEO magic tab is available on the default and modular pages but is not on the modular/text page which is where all the text is, therefore these pages aren't getting the SEO Magic treatment.  we are using the antimatter theme.

I've made sure the page is published and the box is ticked but this hasn't helped thus far.

Any help gratefully received

**Comment by rhukster** [comment]
SEO-Magic is intentionally not included for modular sub pages because the SEO based on the 'parent' page.  When a page is scanned it is crawled by SEO magic like a user browsing the page.  This is not possible to do for modular sub-pages because they are just building blocks that make up a parent modular pages, they are not routable directly by themselves and have no direct way of viewing them via a browser.
