### ISSUE TITLE
Download button appearance

### ISSUE THREAD

**Issue by tomamr** [getgrav/grav-premium-issues#285]
On my website, not all download buttons look the same. Where can this be controlled? Ideally, the look of the sample buttons as in the downloads-pro sample site would be ideal. How can this be achieved?

Thanks, Tom

**Comment by w00fz** [comment]
This is mainly controlled via CSS. Downloads pro offers built-in CSS options that you can opt-out from if you want to provide your very own styling. Otherwise it should be looking very close to the demo. 
The demo is built with Grav’s default Quark theme to ensure the styling is easily adaptable.
If you are seeing inconsistent styling I can only assume your theme is somewhat conflicting with the built-in CSS and it needs some tweaking.

If you have an URL or screenshot to better understand where the inconsistency might be, we can try and help with the styling, however know that every theme is going to have its own styling and Downloads won’t be able to satisfy all circumstances.

**Comment by tomamr** [comment]
Can I send you that information via Email?

Thanks, Tom

**Comment by rhukster** [comment]
A URL can be sent to premium (at) getgrav.org if you would prefer to not share it here.
