### ISSUE TITLE
[nextgen-editor] Can not buy plugin because of XSS issue - please resolve

### ISSUE THREAD

**Issue by the-s-a-m** [getgrav/grav-premium-issues#287]
When I try to buy this plugin I get an XSS-issue. Therefore I can not buy it
![XSS-issue](https://user-images.githubusercontent.com/6050624/171587669-4512b9f5-184a-48c5-931e-d35a149e4405.PNG)
.

**Comment by w00fz** [comment]
We are using Gumroad for our payment system, which is built on top of Stripe.
Both Gumroad and Stripe are trustworthy, I’ve never seen an ad block stopping those domains, most of the internet would stop working if that was the case.

You can perhaps try purchasing from our website rather than directly from Gumroad (https://getgrav.org/premium/nextgen-editor)

but I suspect what you have there is a false-positive.
