### ISSUE TITLE
[typhoon] Table header too dark in dark scheme

### ISSUE THREAD

**Issue by sebastian0119** [getgrav/grav-premium-issues#293]
Hi there,
I believe there is some bug in Typhoon's dark scheme:
When displaying table headers in the light scheme, everything is fine.
But when switching to the dark scheme, table headers are dark blue and not readable.

See also attached screenshots.
![Table header in light scheme](https://user-images.githubusercontent.com/52871458/177633955-ed3f6517-af90-4656-b537-35cacd625943.jpg)
![Table header in dark scheme](https://user-images.githubusercontent.com/52871458/177633958-e30442d3-fc74-4fca-afd9-8baa9e9ab0dd.jpg)

Regards,
Sebastian

**Comment by rhukster** [comment]
I'll look into this.  Thanks.

**Comment by rhukster** [comment]
This is due to a change in how the Typography plugin works.  To fix this you will need to edit your `template/partials/theme-variables.html.twig` file and change the `prose_style` entry:

```
{% set prose_style = 'prose md:prose-md dark:prose-invert' %}
```

This will require a recompile of the CSS, so please follow the docs to do that. I've also fixed this in the next release.

**Comment by rhukster** [comment]
<img width="1082" alt="CleanShot 2022-07-25 at 13 48 43@2x" src="https://user-images.githubusercontent.com/1084697/180862233-d5e7becb-d3ea-447c-ba6d-89c42ea12409.png">

btw, here's a quick screenshot with the table titles rendering correctly.

**Comment by rhukster** [comment]
fixed for next release
