### ISSUE TITLE
[algolia-pro] Previews/Snippets in CLI and instantsearch are different

### ISSUE THREAD

**Issue by Sogl** [getgrav/grav-premium-issues#341]
Default `pages` index.

When I do a search in the console, the snippet shows me the part of the text where the word was found (the word itself is highlighted):

<img width="1125" alt="image" src="https://user-images.githubusercontent.com/7556290/217307111-65df8f80-5f32-43b4-af02-65134a76d76d.png">

In `instantsearch` I see the very beginning of a text or paragraph where there is no search word yet (there is nothing to highlight):
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/7556290/217308254-c7067f4c-1c8b-4682-be15-0a312f899bce.png">

How can this be changed?

**Comment by rhukster** [comment]
@w00fz in the CLI i'm using `snippet` that contains markup to identify the highlighted words, is the instant search results able to use this?

**Comment by w00fz** [comment]
Instasearch already implements highlighting the found keyword. This can be confirmed on https://learn.getgrav.org

<img width="1166" alt="CleanShot 2023-09-08 at 21 15 05@2x" src="https://github.com/getgrav/grav-premium-issues/assets/11734/47805954-b119-45d0-8719-8cba66344e6f">


What am I missing?

**Comment by Sogl** [comment]
@w00fz If you have a small paragraph it will be in the snippet, but if you are looking for something that is in a large paragraph closer to the middle or end of it, there will be nothing in the snippet.

Examples from Grav Learn:

1. With `loadHeaderProperty` search word:
<img width="1148" alt="image" src="https://github.com/getgrav/grav-premium-issues/assets/7556290/24b1d1b3-803c-41e1-ad8e-e7a1da012ede">

The paragraph is large and the word you are looking for is near the end of the paragraph: https://learn.getgrav.org/17/api#class-grav-framework-flex-pages-flexpageobject

<img width="930" alt="image" src="https://github.com/getgrav/grav-premium-issues/assets/7556290/1998e837-f766-4487-b50a-83f1d426e282">

2. With the word `flex` example should be found on page 12 (from 1 to 11 paragraphs are small and snippets immediately have highlighting, I also excluded variants where the word Flex is in the breadcrumbs):
<img width="1141" alt="image" src="https://github.com/getgrav/grav-premium-issues/assets/7556290/b952139c-7f8d-4223-a69a-439c50117971">

The word you are looking for is at the end of the paragraph, so it doesn't make it into the snippet:
https://learn.getgrav.org/17/basics/installation#option-1-install-from-zip-package

<img width="1367" alt="image" src="https://github.com/getgrav/grav-premium-issues/assets/7556290/4179dac2-16bb-4b0d-83f5-6250eb6099c8">

---

My project is medical documentation, and there are some pretty big paragraphs in there, so most of the time the snippets don't show what was found at all.

**Comment by w00fz** [comment]
@Sogl The UI also uses the `<ais-snippet>` component to display the output highlighted, but because it's missing the key elements on the returned payload for `summary`, it doesn't highlight anything.  The UI just populates the `summary` the way it's received back from Algolia Pro, missing the highlighted keywords in some circumstances, as you are experiencing.

What you can do is to instead base that content rendering off of the `content` attribute instead of `summary`. This will undoubtedly make it a much lengthier context, but this seems to be exactly what you are looking  for.

To achieve this, you can [override `hits_preview.html.twig`](https://getgrav.org/premium/algolia-pro/docs/frontend#override-templates) in your theme and modify the bit that references the `summary` attribute to instead point to `content` (at around line 58).

```twig
<ais-snippet
  attribute="content" {# <- from `summary` to `content` #}
  :hit="selected"
  highlighted-tag-name="span"
  :class-names="{
    'ais-Snippet': 'leading-normal text-left text-gray-800 dark:text-gray-300 mt-4 m-auto break-words mb-4',
    'ais-Snippet-highlighted': 'bg-transparent text-algolia-pro',
  }"
></ais-snippet>
```

**Comment by Sogl** [comment]
@w00fz Thank you! Now the CLI output and the instantsearch snippet look the same, which is what I needed.
