### ISSUE TITLE
[nextgen-editor] Line break in table cell

### ISSUE THREAD

**Issue by newmedicine** [getgrav/grav-premium-issues#346]
I'm aware of the limitations of Markdown tables but is there a way of inserting a line break in a table cell? 

I can enter a `<br/>` into a cell to create the line break, after which saving the page renders correctly, but if I save the page again (this time without a `<br/>`) the table "disintegrates".

Nextgen editor  v1.1.13 
Admin panel  v1.10.39

**Comment by duronflo** [comment]
I encouter same behaviour but no answer so far for me :( 

https://github.com/getgrav/grav-premium-issues/issues/333

**Comment by newmedicine** [comment]
Apparently nextgen-editor is probably going to be pulled permanently due to licensing disputes with CKSource
________________________________

**Comment by w00fz** [comment]
> Apparently nextgen-editor is probably going to be pulled permanently due to licensing disputes with CKSource

This is no longer the case. We are in talks with CKSource and after we are done finalizing the paperwork, we will reintroduce NextGen to the Premium marketplace.

---

As for new lines in tables, unfortunately, this is just a limitation with markdown tables and our mechanism of handling the markdown to html back and forth is clearly not robust enough for this specific case. This case is particularly harder because Markdown only allows inline HTML elements within a table cell (links, bold, italic, etc), allowing any arbitrary HTML element means also allowing block elements, like in the case of #333 where an `iframe` is tried to be embedded.  

It will require more investigation for a viable solution but I would suggest instead to go with a full HTML table instead (this is what we end doing often), as a markdown table is just extremely limited.

**Comment by w00fz** [comment]
I was able to get newlines (`<br />`) preserved in tables. This will solve the original reported issue.
It will be available in v1.1.15 when we get it back into the marketplace.
