### ISSUE TITLE
Link to issue tracker shows closed issues

### ISSUE THREAD

**Issue by NicoHood** [getgrav/grav-premium-issues#39]
https://getgrav.org/premium/typhoon/docs#learn-how-to-use-the-full-power-of-typhoon

This will link to https://github.com/getgrav/grav-premium-issues/issues?q=label:typhoon
But shows all closed issues. For github it is very common to only show open issues:
https://github.com/getgrav/grav-premium-issues/labels/typhoon

**Comment by w00fz** [comment]
This is on purpose. Since this is a monolithic issues repository, the shortcut is to filter the subject of the product. 
By allowing to see both open and closed, you can then also make sure something has not been already asked or resolved, since this is not only for bug reports but also questions.

If you are then only interested in the open issues, it's easy enough to just click the Open tab at the top, reorder or filter even further by GitHub tools. Really that link serves just a starting point shortcut.
