### ISSUE TITLE
[typhoon] Need verification - get DL Error on Fonts (from Firefox) with "raw-grav+typhoon"-Install

### ISSUE THREAD

**Issue by myadminnet** [getgrav/grav-premium-issues#396]
- Installed fresh grav on test-server @ https://ds-easy.com/grav-admin
- Installed typhoon + activated theme
- no other config changes or modifications
- cleaned cache + browser hard refresh (F5)

**result: Error 500.. on all theme-fonts**

```
downloadable font: download failed (font-family: "Inter var" style:italic weight:100..900 stretch:100 src index:0): status=2147746065 source: https://ds-easy.com/grav-admin/user/themes/typhoon/fonts/Inter-italic.var.woff2?v=3.19
downloadable font: download failed (font-family: "Inter var" style:normal weight:100..900 stretch:100 src index:0): status=2147746065 source: https://ds-easy.com/grav-admin/user/themes/typhoon/fonts/Inter-roman.var.woff2?v=3.19 
```
It's online - so you can see yourself. 

I am working on another project - and I am stuck with changing the font (according to the doc's), after I started fresh I discovered this first time... since I thought the problems is caused by my changes (those you can't see here - the WIP version is on Linode)

Thx in advance for taking the time! :-)

PS: file rights

![grafik](https://github.com/getgrav/grav-premium-issues/assets/135846140/93b6d817-0be0-415b-a910-e31166b390fa)

**Comment by rhukster** [comment]
maybe your webserver is not configured to handle/serve .woff2 font files?

**Comment by rhukster** [comment]
Just FYI 500 Errors are from the webserver saying that it couldn't handle the request.  If the files could not be found, it would be a 404 error.  A 500 error is usually related to server misconfiguration or setup.  Not a Grav, and probably not even a PHP issue.  You should take a look in your webserver's error log. That will give you a  more in-depth 500 error that should tell you what the problem is.
