### ISSUE TITLE
[lightbox-gallery] How to enable Day/Night Mode Switch in the Gallery?

### ISSUE THREAD

**Issue by stbs01** [getgrav/grav-premium-issues#455]
Hi!

I am using a https://github.com/paulmassen/grav-theme-hyde Grav Theme (v0.2.2) with a Premium Lightbox Gallery Plugin (v1.0.6) on a Linux VPS Server. Now I have the following problem with the Lightbox Gallery Plugin:

Is it possible to turn on switching between the day and night modes in the gallery? I mean, change the background color from black to white and vice versa.

If you go to http://draft.teimur-bek-safiuli.com/works - you will see how it works now - with the black background only.

Thanks for your help!

Best,
Teimur

studio@teimur-bek-safiuli.com

P.S. I have a pretty experienced guy who helps me to build my artist portfolio website, but here he cant help me anymore, thats why I need your help 🙏🏼

**Comment by rhukster** [comment]
Pretty sure Glightbox only comes with a single dark theme.  The script itself is themeable: https://github.com/biati-digital/glightbox/blob/master/README.md#themeable

But i've only every done minor changes via CSS overrides, not providing a whole new theme.  Typically galleries are on black because images tend to look better on dark backgrounds. These kinds of custom works are not really something i can support here.  You need to pay a developer to do this level of customization.
