### ISSUE TITLE
[typhoon] Content works with template but not manually

### ISSUE THREAD

**Issue by spinningjenny69** [getgrav/grav-premium-issues#462]
When i tried to just install grav with the admin plugin and then copy the one page demo into the folders, everything worked fine. I could edit them and so on, but when i tried to copy the file contents from the one page demo pages markdown files into a newly created file using the admin plugin, it didnt work. The content gets displayed, but not in columns or any other configuration options.
![Screenshot from 2024-11-04 18-23-38](https://github.com/user-attachments/assets/40ce5a3a-87c9-4fc1-bb71-cfba23cfca3d)
![Screenshot from 2024-11-04 18-23-18](https://github.com/user-attachments/assets/ceea8523-85c4-4616-94e0-317ccd1ddf08)

The interesting thing is, that when i copied the files into grav and it worked, they all had their own respective templates. When i create a page using the admin plugin, then i just choose the default template, because everything else is irrelevant. I think it has something to do with that but i have literally no idea how i can fix this.

**Comment by rhukster** [comment]
I need a little more detail to fully understand what you are trying to do.  From the second screenshot it looks like you have a 'features' submodular page.  If you wanted to duplicate that page, you can simply use the 'copy' button in the toolbar, this will create a copy.  If you want to do it manually you need to make sure you set the Advanced -> Page Template to "Features" or you will not get the proper rendering.

**Comment by spinningjenny69** [comment]
Sorry for the confusion. 
If i do everything like it is written here it works fine. [](https://github.com/trilbymedia/grav-skeleton-typhoon-onepage)

BUT. When i try to copy a page like this one: [](https://github.com/trilbymedia/grav-skeleton-typhoon-onepage/blob/develop/pages/01.home/02._highlights/features.md) so essentially what i have in the second screenshot, and add that to a new page i created in grav using the admin plugin for example called test that is supposed to be a subpage, then it doesnt show up like in the first screenshot.

I have installed the theme correctly and all plugins but it simply doesnt display the format, for example, variation: horizontal or features: like in the second screenshot.

Now my guess was that this is because of the template, since when i do everything like in the onepage example all the pages have a custom template, that i cant use. 
![Screenshot from 2024-11-04 18-50-27](https://github.com/user-attachments/assets/70442cf2-c657-4e7c-9dc8-a443b1fdac33)

So my question is i guess: why does it work when i simply copy the demo files, but i can't use the same frontmatter on any other page?

**Comment by rhukster** [comment]
First thing I notice and you can see this in the link you provided: https://github.com/trilbymedia/grav-skeleton-typhoon-onepage/blob/develop/pages/01.home/02._highlights/features.md

The spacing of the YAML is incorrect and not valid, so the file will not be parsed correctly. Fix that and see if that helps.

**Comment by spinningjenny69** [comment]
I already fixed that. But even all the other pages like the columns or the callout don't work

**Comment by rhukster** [comment]
Ok, then the next thing to understand is the 'features' template is  a modular template, and that means it only works in a 'modular' parent page.  You can see this in the onepage demo skeleton, the parent page is modular, and the subpages of this parent page are the modular subpages. The front matter defines custom fields and those fields are inherently tied to the template.  In the admin you should see those feature in the conent tab. If you don't see them then you don't have the correct template set.. should be features as mentioned earlier.  

Ok, so note, you cannot have a features page as a standalone page.  You must have a modular parent page, and set it up like th modular subpage in the demo, then have features as a child of this modular page.  This is fundamentally because modular subpages don't inherit from the base.html.twig template, so they don't have the styling/header/footer/css/js etc that the base sets up.  They are intended to be little 'blocks', not 'pages'. More details here: https://learn.getgrav.org/17/content/modular

Is this what you are trying to do? create a new page with just 'features' on it???

**Comment by spinningjenny69** [comment]
ok thank you. i will look around the docs some more but this is very helpful

**Comment by spinningjenny69** [comment]
oh my god it works. I have not the slightest idea why, but as soon as i wrote the filename for every modular page like this: _test or _asdfadbva then it works. I have never in my life been doubting myself so hard just for such a simple thing to make it work
