### ISSUE TITLE
[nextgen-editor] Drag and drop from page media does not work

### ISSUE THREAD

**Issue by vieiderr** [getgrav/grav-premium-issues#51]
I can not insert images (jpg, png, ...) from pagemedia. Installed Grav 1.7.6

As soon as I take the "default editor" drag and drop works..

Please help.

best regards,
robert

**Comment by w00fz** [comment]
Hi @vieiderr , I am not able to reproduce this error, I can successfully upload images to the Page Media and then drag them into the NextGen Editor.

Can you check in your Browser Developer Console if you are getting any JS error? Did you notice this happening perhaps after you installed some other plugin?

Any detail that can help identify the issue is appreciated, unfortunately I don't really have enough information that can pin-point the problem.

**Comment by w00fz** [comment]
hello @vieiderr, just following up with you to see if you have resolved the issue or if this is still a problem. If it is, could you 
 provide further details in that regards, by following the instructions above?

Thank you,
