### ISSUE TITLE
[Typhoon] Text in place of Header Image

### ISSUE THREAD

**Issue by sorat0mo** [getgrav/grav-premium-issues#71]
This feature is in Admin Panel, don't understand why this is absent in Typhoon.

**Comment by rhukster** [comment]
Because Typhoon is a site theme that 99.9% of the time will have a graphical logo. The admin is intended to be viewed by administrators and clients, and it makes sense that for convenience a quick text logo is acceptable.  No one would do this for a regular site though. If you want, quickly create a text logo and save it as an SVG.  Then you can simply upload that SVG and use that as your logo.  Easy peasy!
