### ISSUE TITLE
[typhoon] Prod CSS NPM Script

### ISSUE THREAD

**Issue by red2678** [getgrav/grav-premium-issues#74]
I see the npm script, in the package.json, to build a prod version of the CSS is still there. Is that used in any fashion now that we are using Tailwind JIT (I do not see the prod file in use anywhere but just making sure)? 

`"prod": "postcss css/site.css -o build/css/site.prod.css --env production --verbose"`

**Comment by rhukster** [comment]
Oh i need to remove that.  It's really not needed anymore.  The `site.css` file is already optimized to contain only the CSS required, just like prod used to have.  The only difference is that prod is still compressed. However, I think the better solution is to just to use Grav's CSS pipeline capabilities to compress and combine the CSS files.  the 'prod' file is not referenced anywhere in the config or twig anymore, so that is really the last reference to it.

Thanks for bringing it up!
