### ISSUE TITLE
[Typhoon] Social Links, Menu Links and Notices cannot be empty when enabled

### ISSUE THREAD

**Issue by sorat0mo** [getgrav/grav-premium-issues#75]
What I was trying to do:
Delete content in
- Menu Links
- Social Links
- Notices
Section

Expected behaviour:
No remaining links while respective section is **enabled**

What happened:
The deleted links come back. For social links and notices it come back immediately. For Menu Links, both default items come back when there are no links present.

**Comment by sorat0mo** [comment]
Both theme's yaml attached
[yaml.zip](https://github.com/getgrav/grav-premium-issues/files/6208880/yaml.zip)

**Comment by rhukster** [comment]
After reviewing your yaml, you have the exact situation that the 'enabled' was designed to address.  Basically there is a bug in how Grav handles deep levels of inheritance in configuration. The issue is that the default values provided in the theme's YAML have a couple of entries.  When you want to have turn off entries, and you delete the defaults and saves, it actually saves 'nothing'.  So it falls back on the defaults.  The only way to tell that we don't want to use our entries, and not the defaults is to disable them.  You can provide a parent node and just don't provide any entries, but this doesn't work in the admin:

```
footer:
  menu:
  social:
notices:
```

Notice how the menu, social and notices each have their parent node, but no items.  This effectively nulls those out.  However, we have yet to find a solid way to handle this situation in the admin.

So for the admin, just disable the ones you don't want entries for.

**Comment by rhukster** [comment]
BTW, we handled this a little differently for notices. For those each one has it's own toggle rather than a global one.
