### ISSUE TITLE
[instagram-feed] a few questions

### ISSUE THREAD

**Issue by SjoerdSmeets** [getgrav/grav-premium-issues#77]
Hello, last week i purchased the instagram-feed premium plugin, but still have a few questions.

- Does the app created at develop.facebook.com stay 'in development' mode or does it eventually needs to be published?
- Where are the example layouts as shown in the video?
- Why is there no support for the default grav-theme Quark, but only for Typhoon (which i haven't purchased)? 
- Are there other parameters to pull from the instagram api, or is it this limited? 
- How many images can i pull via the plugin, is pagination an option here?

**Comment by rhukster** [comment]
* I've kept an app in development mode and never 'published' it and it continues to work fine.  
* The videos and screenshots use Tailwind CSS (provided by Typhoon) to provide the 'grid layout'.  There is some information on the layouts here: https://getgrav.org/premium/instagram-feed/docs#functionality-customization
* We don't provide a standalone layout because normally you would build this into the theme you are developing or using.  Each theme uses it's own CSS and potentially it's own CSS framework so it doesn't make sense to bundle something like that.  
* Tailwind uses semantic classnames so it makes it very easy to see what's going on, and how to produce that output.  It's really just a wrapper with flexbox, and then each element is set to 1/3 width. 
* You can dump the image and meta objects to see what's available:
   ```
    {{ dump(image, image.meta) }}
    ```
* As far as i know there's no pagination in the API and not sure about a limit.  It uses this PHP API, so we only have access to what it provides: https://github.com/espresso-dev/instagram-basic-display-php
