### ISSUE TITLE
<mark> </mark> tagged words are turning into plain words

### ISSUE THREAD

**Issue by Gurbuuz** [getgrav/grav-premium-issues#92]
When I write something in expert mode inside NextGen Content Editor it transforms my 

"<mark> text here </mark>"

to

"text here"

**Comment by w00fz** [comment]
I tested this but I don't see the issue.
If you type `<mark>foobar</mark>` NextGen properly saves it as such, however it will display only `foobar` because it's an HTML tag. If you are wanting to use HTML snippets that are editable, you need to use the HTML button:

<img width="127" alt="w00fz-2021-04-27_@_13 16 13@2x" src="https://user-images.githubusercontent.com/11734/116307102-c2154080-a75a-11eb-8557-ec1ed200df81.png">

<img width="255" alt="w00fz-2021-04-27_@_13 17 48@2x" src="https://user-images.githubusercontent.com/11734/116307283-fab51a00-a75a-11eb-8601-ff72365a8f33.png">

If you want to style `<mark>` in the editor, then you need to provide custom CSS from your theme or custom plugin.

**Comment by Gurbuuz** [comment]
Hi, 
So the way I'm editing these pages is in "expert" mode, I do all the styling, HTML related code there. Once I'm done with the page I want to move to "normal" mode because it's only there Grammarly works. But doing this means that I have to sacrifice the things I've styled in expert mode, attaching screenshots for a clearer image. 

I want the "normal" mode to not remove anything I've created inside "expert" mode. (You might have noticed that the "br" tag is also removed. 

In expert mode: 
![image](https://user-images.githubusercontent.com/36448058/116356136-2ab3fa00-a7fb-11eb-9150-26fa882b0868.png)


This is how it looks inside the published page
![image](https://user-images.githubusercontent.com/36448058/116356087-140da300-a7fb-11eb-8f30-fc10a71245c1.png)

If I now switch to normal mode from expert mode, 
![image](https://user-images.githubusercontent.com/36448058/116356199-41f2e780-a7fb-11eb-8ceb-8aff52a627d1.png)


It will turn the content into this: 
![image](https://user-images.githubusercontent.com/36448058/116356248-51723080-a7fb-11eb-925f-1582bbf0baaa.png)


And the published page will transform to this: 
![image](https://user-images.githubusercontent.com/36448058/116356343-723a8600-a7fb-11eb-939e-fcf280c0f9c9.png)
